### ISSUE TITLE
Inconsistency for uppercase words?

### ISSUE THREAD

**Issue by dima74** [nalgeon/iuliia#5]
В реализациях на python и javascript (вероятно в других тоже) при транслитерации слов полностью состоящих из заглавных букв может получиться слово содержащее строчные буквы. Например (для схемы `WIKIPEDIA`):

* `ЕЩЁ` → `YeShchYo`
* `ШЁПОТ` → `ShYoPOT`

Это ожидаемое поведение? Мне кажется было бы логично чтобы все буквы полученного слова были заглавными. Например можно использовать uppercase маппинг для буквы если текущая и следующая буквы являются заглавными

**Comment by nalgeon** [comment]
Да, это ожидаемое поведение, но согласен, что получилось криво. Исправлю для питона и js.
